---
- name: "oauth2_proxy | Include pre requisite tasks"
  ansible.builtin.import_tasks:
    file: "pre_requisite.yml"
- name: "oauth2_proxy | Include packages tasks [package install]"
  ansible.builtin.include_tasks:
    file: "packages.yml"
  when:
    - "lookup('ansible.builtin.vars', 'oauth2_proxy', default='')
      not in ['', [], '[]', None]"
    - "lookup('ansible.builtin.vars', 'oauth2_proxy') |
       community.general.json_query(lookup('ansible.builtin.vars',
      'oauth2_proxy_install_package', default='')) == 'true'"
  vars:
    oauth2_proxy_install_package: "[] |
      map(&install_package || 'false', @) | [0]"

# Для OS без пакета (Debian) — install_package: 'false' + download tarball.
- name: "oauth2_proxy | Include download tasks [tarball install]"
  ansible.builtin.include_tasks:
    file: "download.yml"
  when:
    - "lookup('ansible.builtin.vars', 'oauth2_proxy', default='')
      not in ['', [], '[]', None]"
    - "lookup('ansible.builtin.vars', 'oauth2_proxy') |
       community.general.json_query(lookup('ansible.builtin.vars',
      'oauth2_proxy_install_package', default='')) == 'false'"
  vars:
    oauth2_proxy_install_package: "[] |
      map(&install_package || 'false', @) | [0]"
- name: "oauth2_proxy | Include deployment tasks"
  ansible.builtin.import_tasks:
    file: "deploy.yml"
