---
- name: "oauth2_proxy | Install the required packages in Redhat derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_facts']['os_family'] == 'RedHat'"
  block:
    - name: "oauth2_proxy | Update dnf cache"
      ansible.builtin.dnf:
        update_cache: "yes"
    - name: "oauth2_proxy | Install package with dnf"
      ansible.builtin.dnf:
        name: "{{ lookup('ansible.builtin.vars', 'oauth2_proxy_package') }}"
        state: "{{ lookup('ansible.builtin.vars', 'oauth2p_package_state') }}"
- name: "oauth2_proxy | Install the required packages in Debian derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_facts']['os_family'] == 'Debian'"
  block:
    - name: "oauth2_proxy | Update apt cache"
      ansible.builtin.apt:
        update_cache: "yes"
    - name: "oauth2_proxy | Install package with apt"
      ansible.builtin.apt:
        name: "{{ lookup('ansible.builtin.vars', 'oauth2_proxy_package') }}"
        state: "{{ lookup('ansible.builtin.vars', 'oauth2p_package_state') }}"
- name: "oauth2_proxy | Install the required packages in ArchLinux derivatives"
  when:
    - "hostvars[inventory_hostname]['ansible_facts']['os_family'] ==
      'Archlinux'"
  block:
    - name: "oauth2_proxy | Update pacman cache"
      community.general.pacman:
        update_cache: "yes"
    - name: "oauth2_proxy | Install package with pacman"
      community.general.pacman:
        name: "{{ lookup('ansible.builtin.vars', 'oauth2_proxy_package') }}"
        state: "{{ lookup('ansible.builtin.vars', 'oauth2p_package_state') }}"
