---
- name: "oauth2_proxy | Assert that ansible facts gathered successfully"
  ansible.builtin.assert:
    that:
      - "hostvars[inventory_hostname]['ansible_facts']['service_mgr'] is
        defined"
    fail_msg: "'ansible_facts' not found. Please enable facts gathering"
    quiet: "true"
- name: "oauth2_proxy | Assert that system manager is systemd"
  ansible.builtin.assert:
    that:
      - "hostvars[inventory_hostname]['ansible_facts']['service_mgr'] ==
        'systemd'"
    fail_msg: "System manager is not systemd"
    quiet: "true"
- name: "oauth2_proxy | Add the OS specific variables"
  ansible.builtin.include_vars:
    file: "{{ hostvars[inventory_hostname]['ansible_facts']['os_family'] +
      '.yml' }}"
- name: "oauth2_proxy | Set facts about oauth2_proxy role"
  ansible.builtin.set_fact:
    oauth2p_settings: "{{ lookup('ansible.builtin.vars', 'oauth2_proxy') |
      community.general.json_query('[].settings[]') }}"
    oauth2p_package_state: "{{ lookup('ansible.builtin.vars', 'oauth2_proxy') |
      community.general.json_query('[].package_state | [0]') }}"
  when:
    - "lookup('ansible.builtin.vars', 'oauth2_proxy', default='')
      not in ['', [], '[]', None]"
- name: "oauth2_proxy | Assert that oauth2_proxy package state in valid value"
  ansible.builtin.assert:
    that:
      - "lookup('ansible.builtin.vars', 'oauth2p_package_state') in
        ['present', 'latest']"
    fail_msg: "{{ 'package_state must be in `present` or `latest`,
      current is: ' + lookup('ansible.builtin.vars',
      'oauth2p_package_state') }}"
    quiet: "true"
  when:
    - "lookup('ansible.builtin.vars', 'oauth2p_package_state',
      default='') not in ['', [], '[]', None, 'present', 'latest']"
- name: "oauth2_proxy | Set package state to 'present' cause value is not
    defined"
  ansible.builtin.set_fact:
    oauth2p_package_state: "present"
  when:
    - "lookup('ansible.builtin.vars', 'oauth2p_package_state',
      default='') in ['', [], '[]', None]"
- name: "oauth2_proxy | Create catalogs"
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.vars', 'oauth2_proxy_dest') }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  when:
    - "lookup('ansible.builtin.vars', 'oauth2p_settings', default='')
      not in ['', [], '[]', None]"
